django_official_tutriol/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('vote/', include("vote.urls"))
]

vote/urls.py
from django.urls import path
from . import views
app_name = 'vote'
urlpatterns = [path("", views.index, name = "index"),
               path('<int:question_id>', views.detail, name = "detail"),
               path("<int:question_id>/results/",views.results,name = "results"),
               path("<int:question_id>/voting/",views.voting, name = "voting")
               ]

vote/models.py
import datetime

from django.db import models
from django.utils import timezone
# Create your models here.

class Question(models.Model):
    questions_text = models.TextField(max_length=200)
    pub_time = models.DateTimeField('date publish')
    def __str__(self):
        return self.questions_text

    def was_publish_within_one_day(self):
        return timezone.now()-self.pub_time <= datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.TextField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

vote/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,Http404,HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from .models import Question

# Create your views here.

def index_origin(request):
    lastest_question_list = Question.objects.order_by("-pub_time")[:5]
    output = ','.join(q.questions_text for q in lastest_question_list)
    return HttpResponse(output)

def index_use_html(request):
    lastest_question_list = Question.objects.order_by("-pub_time")[:5]
    template = loader.get_template("vote/index.html")
    context = {
        "latest_question_list": lastest_question_list
    }
    return HttpResponse(template.render(context, request))

def index(request):
    latest_question_list = Question.objects.order_by("-pub_time")[:5]
    context = {"latest_question_list": latest_question_list}
    return render(request, "vote/index.html", context)

def detail(request, question_id):
    try:
        question = Question.objects.get(pk = question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exit")
    return render(request,'vote/detail.html',{'question':question})


def results(request, question_id):
    question = get_object_or_404(Question, pk = question_id)
    results = render(request , "vote/results.html",{'question':question})
    return results


def voting(request, question_id):
    question = get_object_or_404(Question, pk = question_id)
    try:
        selected_choice = question.choice_set.get(pk = request.POST["choice"])
    except:
        return render(request, 'vote/detail.html',{'question':question,'error_message': "You didn't select a choice.",})
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse("vote:results"),args = (question.id,))

vote/templates/vote/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'vote:voting' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.questions_text }}</h1></legend>
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice"  id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
<input type="submit" value="Vote">
</form>
</body>
</html>

vote/templates/vote/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'vote:detail' question.id  %} ">{{ question.questions_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

</body>
</html>

vote/templates/vote/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<header>{{ question.questions_text }}</header>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}--{{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</body>
</html>